### ISSUE TITLE
check_data abfragen

### ISSUE THREAD

**Issue by DieterTepe** [michel-cf/micropython-nextion#2]
Wie nutze ich die check_data Methode? Wenn ich zum Beispiel einen Butten b1 anfragen möchte.
Vielleicht können sie ein Beispiel anlegen. Ich möchte gerne aus einen Textfeld ein Text auslesen.

**Comment by DieterTepe** [comment]
Wenn ich wüsste wie ich dir Rückrufmethode Aufrufe dann wäre ich schon ein großen Schritt weiter.

**Comment by michel-cf** [comment]
You need to call it whenever you want to process user input. Best quite frequently.

There is no return value. But you supply a method, this method will be called for each command
`callback(command=self.command, page=self.page, id=self.id, touch_event=self.touch_event)`

```
def nextion_callback(command, page, id, touch_event)
  print('command: %s page: %s id: %s, touch_event: %s' % (coomand, page, id, touch_event))
  

nextion = Nextion()

while True:
  nextion.check_data(self, nextion_callback)

```

**Comment by DieterTepe** [comment]
Ich danke dir sehr für die schnelle Reaktion. Hinweis im  Printbefehl ist ein Schreibfehler "command" und in der ersten Befehlszeile fehlen die :
Aber es läuft schon Mal.

**Comment by DieterTepe** [comment]
Hello Michel,
First of all, thank you very much for your reaction,
The callback works. But when I query a button, I have to
Set chars = self.readinto (self.read_buffer, 7) to use.
Otherwise my program will be interrupted.

If I send a text from the nextion then nothing is recognized.
A text or a variable is then not terminated with FFF either.
How is the procedure there?

Mfg   Dieter
